version: 1.1.2
workflows:
  - subclass: WDL
    primaryDescriptorPath: na # absolute path
    testParameterFiles: na  # absolute path
    readMePath: na # absolute path
    authors:
      - name: JY-C
